title: "Lek's Portfolio"
name: "Lek Man"
description: >- # this means to ignore newlines until "baseurl:"
  "Welcome to my portfolio website. 
  Here you can find my projects and learn more about me."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sophondroplet.github.io"
repository: "sophondroplet/Portfolio-website"
search: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include: 
  - "_pages"

#author profile
author:
  name: "Lek Man"
  avatar: "/assets/images/profile-avatar.jpg" # Path to an image in your repo
  bio: "I'm a developer and researcher passionate about building cool projects. Welcome to my portfolio!"
  location: "Your City, Country"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yourusername"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/yourusername"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://yourwebsite.com"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false
#Applies to all project pages
  - scope:
      path: "_pages/projects"  
    values:
      layout: single
      sidebar:
        nav: projects-nav
      toc: true