title: "Lek's Portfolio"
name: "Lek Man"
description: >- # this means to ignore newlines until "baseurl:"
  "Welcome to my portfolio website. 
  Here you can find my projects and learn more about me."
baseurl: "/Portfolio-website"
url: "https://sophondroplet.github.io"
repository: "sophondroplet/Portfolio-website"
search: true
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include: 
  - "_pages"

#custom css
# custom_css: assets/css/main.css

# sass:
#   sass_dir: _sass
#   style: compressed

#author profile
author:
  name: "Lek Man"
  avatar: "/assets/images/profile/me3.jpg" # Path to an image in your repo
  bio: >-
    Aerospace Engineering undergraduate at UC San Diego, 
    passionate about building robots, drones, and mechatronic 
    systems. I enjoy turning ideas into functional machines through 
    projects, competitions, and collaborations. Welcome to my 
    portfolio!
  location: "9450 Gilman Dr., 
   La Jolla"
  links:
    - label: "Email: manmanleklek@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "manmanleklek@gmail.com"
    - label: "GitHub: sophondroplet"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sophondroplet"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yourusername"
  

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false
#Applies to all project pages
  - scope:
      path: "_pages/projects"  
    values:
      layout: single
      sidebar:
        nav: projects-nav
      toc: true
      toc_sticky: true

  - scope:
      path: "_pages/experiences"  
    values:
      layout: single
      sidebar:
        nav: experiences-nav
      toc: true
      toc_sticky: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache